// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrawData } from "./DrawData";
import type { DrawRequest } from "./DrawRequest";

export type Message = { "type": "init" } | { "type": "resize", "data": { width: number, height: number, } } | { "type": "drawData", "data": DrawData } | { "type": "drawRequest", "data": DrawRequest };
