// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MonitorMode = { "type": "sample" } | { "type": "peak", "data": number } | { "type": "rms", "data": number };
