// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorMode } from "./MonitorMode";

export type SpectrumAnalyzerConfigUpdate = { "type": "fps", "data": number } | { "type": "monitorMode", "data": MonitorMode } | { "type": "decaySpeed", "data": number };
