[alias]
#xtask = "run --package xtask --release --"
xtask = "run --package xtask --release --"

[build]
rustflags = ["-C", "force-frame-pointers=yes"]

[env]
TS_RS_EXPORT_DIR = { value = "./gui/bindings/", relative = true }
